-- appended Task Pricing table

CREATE TABLE IF NOT EXISTS task_pricing (
  id INT AUTO_INCREMENT PRIMARY KEY,
  platform VARCHAR(64) NOT NULL UNIQUE,
  user_reward DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  advertiser_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  meta JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
