uploads = []
generated = []

[[outputs]]
id = "u-s0tSCfyDE9gHy9EIlF3"
uri = "file://tasksearn_backup_20260729_101427.sql"
type = "unspecified"
title = "TasksEarn PostgreSQL Database Backup — 2026-07-29"
